name: "get-fellows-action"
description: "Fetch all the GitHub handles from the Fellows"
author: Bullrich
branding:
  icon: copy
  color: yellow
outputs:
  fellow-handles:
    description: 'A JSON array with all the GitHub handles of the fellows.'
  fellows-map:
    description: 'A JSON array with objects of type { "user": "github-handle", "rank": rank (as a number) }'

runs:
  using: 'docker'
  image: 'Dockerfile'
