name: "get-fellows-action"
description: "Fetch all the GitHub handles from the Fellows"
author: Bullrich
branding:
  icon: users
  color: red
outputs:
  fellows-handles:
    description: 'A JSON array with objects of type { "address": "1e2345...", "rank": rank (as a number), githubHandle: "can be null" }'
  github-handles:
    description: "All the fellows' Github handles separated by commas"

runs:
  using: 'docker'
  image: 'docker://ghcr.io/paritytech/get-fellows-action/action:1.2.0'
